# Generated by Django 5.2.8 on 2025-12-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('kanban_app', '0004_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='auth_app.account'),
            preserve_default=False,
        ),
    ]
